### PR TITLE
how to do?

### PR DESCRIPTION
**Pull request by jaying**

### CODE REVIEW

**Comment by jaying** [comment]
how to do ? can teach me ?

**Comment by jarbogast** [comment]
If you're trying to incorporate our SDK into your application, check out the [README](https://github.com/Adonit/JotTouchSDK/blob/master/README.md) as well as the [Getting Started Guide](http://github.com/Adonit/JotTouchSDK/wiki/Getting-Started-Guide).

If you still have questions you can always email us at developers@adonit.net.

**Comment by jaying** [comment]
Sir can do video step to me?
use what app to SDK
SDK put inside IPAD AIR 2 or jot touch ? @jarbogast 
thank you

**Comment by jarbogast** [comment]
Sorry. I'm just not sure what you're asking.

If you're trying to incorporate our SDK into your application, check out the README as well as the Getting Started Guide.

If you still have questions you can always email us at developers@adonit.net.

**Pull request closed without merging**
